In [36]:
import numpy as np

## Matrices in python

### Scalars

Matrices of $1$ x $1$

In [37]:
s = 5 
s

5

In [38]:
type(s)

int

### Vectors

Matrices with only one dimension 

$1$ x $n$ or $n$ x $1$

In [39]:
v = np.array([1,2,3]) # Row vector
v

array([1, 2, 3])

In [40]:
type(v)

numpy.ndarray

In [41]:
v.shape

(3,)

Reshaping 

In [42]:
v.reshape(1,3) # row vector

array([[1, 2, 3]])

In [43]:
v.reshape(3,1) # column vector

array([[1],
       [2],
       [3]])

### Matrices

Matrices of $m$ x $n$

In [44]:
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
type(m)

numpy.ndarray

In [46]:
m.shape

(2, 3)

## TensorFLow

A Tensor englobes, Scalars, Vectors and Matrices but is mainly a collection os Matrices with dimensions $k$ x $m$ x $n$ (Ranks $0$ to $3$ respectively)

Tensors can be stored in np.arrays

Creating a Tensor

In [47]:
m1 = np.array([[3,2,1],[6,5,4]])
m1

array([[3, 2, 1],
       [6, 5, 4]])

In [48]:
m2 = np.array([[1,2,3],[4,5,6]])
m2

array([[1, 2, 3],
       [4, 5, 6]])

Creating the tensor with the 2 previous matrices

In [49]:
t = np.array([m1,m2]) 
t

array([[[3, 2, 1],
        [6, 5, 4]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [50]:
t.shape # 2 matrices, 2 lines, 3 columns

(2, 2, 3)

Creating the same tensor manually

In [51]:
t1 = np.array([[[3,2,1],[6,5,4]],[[1,2,3],[4,5,6]]])
t1

array([[[3, 2, 1],
        [6, 5, 4]],

       [[1, 2, 3],
        [4, 5, 6]]])

### Operations

For Addition and subtraction, the matrices need to have the same dimentions

However, on python, a Scalar can be added to a Matrix, and it will be added (or subtracted) for each element 

    Addition 

In [52]:
sum = m1+m2
sum

array([[ 4,  4,  4],
       [10, 10, 10]])

    Subtraction

In [53]:
diff = m1-m2
diff

array([[ 2,  0, -2],
       [ 2,  0, -2]])

    Transposing

In [54]:
sum.T

array([[ 4, 10],
       [ 4, 10],
       [ 4, 10]])

In [55]:
diff.T

array([[ 2,  2],
       [ 0,  0],
       [-2, -2]])

In [56]:
v.T #Does not work for 1 dimension arrays

array([1, 2, 3])

    Multiplication

There is the outter and the inner product, here we will use ony the inner (scalar/dot product), which results on a scalar

In [57]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [58]:
np.dot(x,y)

10

In [59]:
np.dot(x,2) #the Scalar 2 is being multiplied by each element, it does not change the shape

array([2, 4, 6])

When multiplying matrices, the colums of the first must match the lines of the second

So the multiplication rule will be as follows:

$m$ x $n * n$ x $k = m$ x $k$

Example:

$2$ x $3 * 3$ x $4 = 2$ x $4$

It works for vectors as well

In [63]:
np.dot(sum,diff) #since they are 2x3 * 2x3 the multiplication will not work

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [61]:
x = sum.T # is being transposed to respect the rule above
y = diff

In [62]:
np.dot(x,y) # 3x2 * 2x3 = 3x3 matrix

array([[ 28,   0, -28],
       [ 28,   0, -28],
       [ 28,   0, -28]])